<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
	<LangVersion>preview</LangVersion>
	  <AssemblyName>PCRA</AssemblyName>
	  <RootNamespace>PCRA</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	 <ApplicationIcon>Assets\tex-logo.ico</ApplicationIcon>
	 <Title>Tex C.lab</Title>
	 <Product>$(AssemblyName)</Product>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Folder Include="Styles\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Docs\build\UserManual.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
	  <Reference Include="TexControllers">
		  <HintPath>libs/TexControllers.dll</HintPath>
	  </Reference>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
</Project>
